_BASE_: "../configs/Base-RCNN-FPN.yaml"
DATALOADER:
  COPY_PASTE: True
  COPY_PASTE_RATE: 1.0
  VISUALIZE_COPY_PASTE: False
  COPY_PASTE_RANDOM_NUM: True
  COPY_PASTE_MIN_RATIO: 0.3
  COPY_PASTE_MAX_RATIO: 1.0
  NUM_WORKERS: 0
MODEL:
  ROI_HEADS:
    USE_DROPLOSS: True  # 或者 False
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  WEIGHTS: 'http://dl.fbaipublicfiles.com/cutler/checkpoints/dino_RN50_pretrain_d2_format.pkl'
  MASK_ON: True
  BACKBONE:
    FREEZE_AT: 0
  RESNETS:
    DEPTH: 50
    NORM: "SyncBN"
    STRIDE_IN_1X1: False
  FPN:
    NORM: "SyncBN"
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  ROI_HEADS:
    NAME: CustomCascadeROIHeads
    NUM_CLASSES: 2
    SCORE_THRESH_TEST: 0.0
    POSITIVE_FRACTION: 0.25
    USE_DROPLOSS: True
    DROPLOSS_IOU_THRESH: 0.01
  RPN:
    POST_NMS_TOPK_TRAIN: 4000
    NMS_THRESH: 0.65
  CONDINST:
    TOPK_PROPOSALS_PER_IM: 64
    MASK_BRANCH:
      OUT_CHANNELS: 16
  BOXINST:
    ENABLED: True
    BOTTOM_PIXELS_REMOVED: 10
    PAIRWISE:
      SIZE: 3
      DILATION: 2
      COLOR_THRESH: 0.3
DATASETS:
  TEST: ("ISBI_test",)
  TRAIN: ("ISBI_train",)
  VAL: ("ISBI_val",)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.00005
  STEPS: (2500,)
  MAX_ITER: 10000
  GAMMA: 0.02
  CLIP_GRADIENTS:
    CLIP_TYPE: norm
    CLIP_VALUE: 1.0
    ENABLED: true
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
INPUT:
  MIN_SIZE_TRAIN: (240, 320, 480, 640, 672, 704, 736, 768, 800, 1024)
  MAX_SIZE_TRAIN: 1333
  MASK_FORMAT: "bitmask"
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD : 500   #每隔5000轮验证一次
  PRECISE_BN:
    ENABLED: True
    NUM_ITER: 200
  DETECTIONS_PER_IMAGE: 100
OUTPUT_DIR: ""